{
    "swagger": "2.0",
    "basePath": "/gotapi/test",
    "info": {
        "title": "Event without Interval",
        "version": "2.0.0",
        "description": ""
    },
    "consumes": [
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "paths": {
        "/noInterval1": {
            "get": {
                "operationId": "testNoInterval1Get",
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "query",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/NoIntervalResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0,
                                "test": "test"
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "testNoInterval1Put",
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "formData",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/NoIntervalEvent"
                    },
                    "examples": {
                        "application/json": {
                            "servieId": "xxxxx",
                            "profile" : "test",
                            "attribute" : "noInterval1",
                            "test": "test"
                        }
                    }
                }
            },
            "delete": {
                "operationId": "testNoInterval1Delete",
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "query",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0
                            }
                        }
                    }
                }
            }
        },
        "/noInterval2": {
            "get": {
                "operationId": "testNoInterval2Get",
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "query",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/NoIntervalResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0,
                                "test": "test"
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "testNoInterval2Put",
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "formData",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/NoIntervalEvent"
                    },
                    "examples": {
                        "application/json": {
                            "servieId": "xxxxx",
                            "profile" : "test",
                            "attribute" : "noInterval2",
                            "test": "test"
                        }
                    }
                }
            },
            "delete": {
                "operationId": "testNoInterval2Delete",
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "query",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0
                            }
                        }
                    }
                }
            }
        },
        "/interval": {
            "get": {
                "operationId": "testIntervalGet",
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "query",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/NoIntervalResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0,
                                "test": "test"
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "testIntervalPut",
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "formData",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "interval",
                    "description": "インターバル。",
                    "in": "formData",
                    "required": true,
                    "type": "integer",
                    "format": "int64"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/IntervalEvent"
                    },
                    "examples": {
                        "application/json": {
                            "servieId": "xxxxx",
                            "profile" : "test",
                            "attribute" : "interval",
                            "test": "test"
                        }
                    }
                }
            },
            "delete": {
                "operationId": "testIntervalDelete",
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [{
                    "name": "serviceId",
                    "description": "サービスID。",
                    "in": "query",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "product": "Example System",
                                "version": "1.0",
                                "result": 0
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "NoIntervalResponse": {
            "type": "object",
            "allOf": [{
                "$ref": "#/definitions/CommonResponse"
            }, {
                "$ref": "#/definitions/NoIntervalInfo"
            }]
        },
        "NoIntervalEvent": {
            "type": "object",
            "allOf": [{
                "$ref": "#/definitions/CommonEvent"
            }, {
                "$ref": "#/definitions/NoIntervalInfo"
            }]
        },
        "NoIntervalInfo": {
            "type": "object",
            "required": ["test"],
            "properties": {
                "test": {
                    "type": "string",
                    "title": "test",
                    "description": "test"
                }
            }
        },
        "IntervalResponse": {
            "type": "object",
            "allOf": [{
                "$ref": "#/definitions/CommonResponse"
            }, {
                "$ref": "#/definitions/IntervalInfo"
            }]
        },
        "IntervalEvent": {
            "type": "object",
            "allOf": [{
                "$ref": "#/definitions/CommonEvent"
            }, {
                "$ref": "#/definitions/IntervalInfo"
            }]
        },
        "IntervalInfo": {
            "type": "object",
            "required": ["test"],
            "properties": {
                "test": {
                    "type": "string",
                    "title": "test",
                    "description": "test"
                }
            }
        },
        "EventRegistrationResponse": {
            "type": "object",
            "allOf": [{
                "$ref": "#/definitions/CommonResponse"
            }]
        },
        "EventUnregistrationResponse": {
            "type": "object",
            "allOf": [{
                "$ref": "#/definitions/CommonResponse"
            }]
        },
        "CommonResponse": {
            "type": "object",
            "required": [
                "result",
                "product",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "title": "処理結果",
                    "description": "0:正常応答<br>0以外:異常応答"
                },
                "product": {
                    "type": "string",
                    "title": "システム名",
                    "description": "DeviceConnectシステムの名前。"
                },
                "version": {
                    "type": "string",
                    "title": "システムバージョン",
                    "description": "DeviceConnectシステムのバージョン名。"
                },
                "hmac": {
                    "type": "string",
                    "title": "署名",
                    "description": "レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
                }
            }
        },
        "CommonEvent": {
            "type": "object",
            "required": [
                "serviceId",
                "profile",
                "interface",
                "attribute"
            ],
            "properties": {
                "serviceId": {
                    "type": "string",
                    "title": "サービスID",
                    "description": "イベントを送信したサービスのID"
                },
                "profile": {
                    "type": "string",
                    "title": "プロファイル名",
                    "description": "プロファイル名。"
                },
                "interface": {
                    "type": "string",
                    "title": "インターフェース名",
                    "description": "インターフェース名。"
                },
                "attribute": {
                    "type": "string",
                    "title": "アトリビュート名",
                    "description": "アトリビュート名。"
                }
            }
        }
    }
}